import type { TriviaQuestion } from '@/types/trivia'

/**
 * 45 hard-coded trivia questions about movies and TV shows from the 1990s onward.
 * Each statement is factually verifiable. Approximately 50/50 split between
 * true (answer: true) and false (answer: false) correct answers.
 */
export const triviaQuestions: TriviaQuestion[] = [
  // ── TRUE statements ──
  {
    id: 'q01',
    statement: 'This film won the Academy Award for Best Picture.',
    answer: true,
    title: 'The Silence of the Lambs',
    year: 1991,
    mediaType: 'movie',
    difficulty: 'easy',
  },
  {
    id: 'q02',
    statement: 'This film was directed by Quentin Tarantino.',
    answer: true,
    title: 'Pulp Fiction',
    year: 1994,
    mediaType: 'movie',
    difficulty: 'easy',
  },
  {
    id: 'q03',
    statement: 'Leonardo DiCaprio starred in this film.',
    answer: true,
    title: 'Titanic',
    year: 1997,
    mediaType: 'movie',
    difficulty: 'easy',
  },
  {
    id: 'q04',
    statement: 'This series ran for 10 seasons.',
    answer: true,
    title: 'Friends',
    year: 1994,
    mediaType: 'tv',
    difficulty: 'easy',
  },
  {
    id: 'q05',
    statement: 'This film features the quote "I see dead people."',
    answer: true,
    title: 'The Sixth Sense',
    year: 1999,
    mediaType: 'movie',
    difficulty: 'easy',
  },
  {
    id: 'q06',
    statement: 'Keanu Reeves plays the lead character in this film.',
    answer: true,
    title: 'The Matrix',
    year: 1999,
    mediaType: 'movie',
    difficulty: 'easy',
  },
  {
    id: 'q07',
    statement: 'This show was created by David Chase.',
    answer: true,
    title: 'The Sopranos',
    year: 1999,
    mediaType: 'tv',
    difficulty: 'medium',
  },
  {
    id: 'q08',
    statement: 'This film is set primarily in New Zealand.',
    answer: true,
    title: 'The Lord of the Rings: The Fellowship of the Ring',
    year: 2001,
    mediaType: 'movie',
    difficulty: 'medium',
  },
  {
    id: 'q09',
    statement: 'Heath Ledger won a posthumous Oscar for this film.',
    answer: true,
    title: 'The Dark Knight',
    year: 2008,
    mediaType: 'movie',
    difficulty: 'easy',
  },
  {
    id: 'q10',
    statement: 'This animated film was Pixar\'s first feature.',
    answer: true,
    title: 'Toy Story',
    year: 1995,
    mediaType: 'movie',
    difficulty: 'easy',
  },
  {
    id: 'q11',
    statement: 'Bryan Cranston plays the lead character in this series.',
    answer: true,
    title: 'Breaking Bad',
    year: 2008,
    mediaType: 'tv',
    difficulty: 'easy',
  },
  {
    id: 'q12',
    statement: 'This film was shot entirely in black and white.',
    answer: true,
    title: 'Schindler\'s List',
    year: 1993,
    mediaType: 'movie',
    difficulty: 'medium',
  },
  {
    id: 'q13',
    statement: 'This show is based on a series of novels by George R.R. Martin.',
    answer: true,
    title: 'Game of Thrones',
    year: 2011,
    mediaType: 'tv',
    difficulty: 'easy',
  },
  {
    id: 'q14',
    statement: 'This film takes place mostly inside a computer simulation.',
    answer: true,
    title: 'The Matrix',
    year: 1999,
    mediaType: 'movie',
    difficulty: 'easy',
  },
  {
    id: 'q15',
    statement: 'This film won the Palme d\'Or at the Cannes Film Festival.',
    answer: true,
    title: 'Parasite',
    year: 2019,
    mediaType: 'movie',
    difficulty: 'medium',
  },
  {
    id: 'q16',
    statement: 'Joaquin Phoenix won the Best Actor Oscar for this film.',
    answer: true,
    title: 'Joker',
    year: 2019,
    mediaType: 'movie',
    difficulty: 'medium',
  },
  {
    id: 'q17',
    statement: 'This series is set in Hawkins, Indiana.',
    answer: true,
    title: 'Stranger Things',
    year: 2016,
    mediaType: 'tv',
    difficulty: 'easy',
  },
  {
    id: 'q18',
    statement: 'This film grossed over $2 billion worldwide.',
    answer: true,
    title: 'Avengers: Endgame',
    year: 2019,
    mediaType: 'movie',
    difficulty: 'medium',
  },
  {
    id: 'q19',
    statement: 'This show premiered on HBO in 2008.',
    answer: true,
    title: 'Breaking Bad',
    year: 2008,
    mediaType: 'tv',
    difficulty: 'hard',
  },
  {
    id: 'q20',
    statement: 'This film was directed by Christopher Nolan.',
    answer: true,
    title: 'Inception',
    year: 2010,
    mediaType: 'movie',
    difficulty: 'easy',
  },
  {
    id: 'q21',
    statement: 'Sandra Bullock starred in this Oscar-winning film.',
    answer: true,
    title: 'Gravity',
    year: 2013,
    mediaType: 'movie',
    difficulty: 'medium',
  },
  {
    id: 'q22',
    statement: 'This Korean series became Netflix\'s most-watched show in 2021.',
    answer: true,
    title: 'Squid Game',
    year: 2021,
    mediaType: 'tv',
    difficulty: 'easy',
  },

  // ── FALSE statements ──
  {
    id: 'q23',
    statement: 'This film was directed by Steven Spielberg.',
    answer: false,
    title: 'The Shawshank Redemption',
    year: 1994,
    mediaType: 'movie',
    difficulty: 'medium',
  },
  {
    id: 'q24',
    statement: 'Tom Hanks starred in this film.',
    answer: false,
    title: 'Good Will Hunting',
    year: 1997,
    mediaType: 'movie',
    difficulty: 'medium',
  },
  {
    id: 'q25',
    statement: 'This show aired on NBC.',
    answer: false,
    title: 'The Wire',
    year: 2002,
    mediaType: 'tv',
    difficulty: 'medium',
  },
  {
    id: 'q26',
    statement: 'This film is a sequel.',
    answer: false,
    title: 'Inception',
    year: 2010,
    mediaType: 'movie',
    difficulty: 'easy',
  },
  {
    id: 'q27',
    statement: 'This film won the Best Picture Oscar.',
    answer: false,
    title: 'Saving Private Ryan',
    year: 1998,
    mediaType: 'movie',
    difficulty: 'hard',
  },
  {
    id: 'q28',
    statement: 'Brad Pitt directed this film.',
    answer: false,
    title: 'Fight Club',
    year: 1999,
    mediaType: 'movie',
    difficulty: 'medium',
  },
  {
    id: 'q29',
    statement: 'This film is based on a Stephen King novel.',
    answer: false,
    title: 'Silence of the Lambs',
    year: 1991,
    mediaType: 'movie',
    difficulty: 'medium',
  },
  {
    id: 'q30',
    statement: 'This series premiered in the 1990s.',
    answer: false,
    title: 'The Office',
    year: 2005,
    mediaType: 'tv',
    difficulty: 'easy',
  },
  {
    id: 'q31',
    statement: 'This film was produced by Marvel Studios.',
    answer: false,
    title: 'The Dark Knight',
    year: 2008,
    mediaType: 'movie',
    difficulty: 'easy',
  },
  {
    id: 'q32',
    statement: 'This film takes place in the future.',
    answer: false,
    title: 'The Grand Budapest Hotel',
    year: 2014,
    mediaType: 'movie',
    difficulty: 'easy',
  },
  {
    id: 'q33',
    statement: 'This show was created by Vince Gilligan.',
    answer: false,
    title: 'The Sopranos',
    year: 1999,
    mediaType: 'tv',
    difficulty: 'hard',
  },
  {
    id: 'q34',
    statement: 'This animated film was made by DreamWorks.',
    answer: false,
    title: 'Finding Nemo',
    year: 2003,
    mediaType: 'movie',
    difficulty: 'easy',
  },
  {
    id: 'q35',
    statement: 'Meryl Streep appears in this film.',
    answer: false,
    title: 'Black Swan',
    year: 2010,
    mediaType: 'movie',
    difficulty: 'medium',
  },
  {
    id: 'q36',
    statement: 'This film is rated G.',
    answer: false,
    title: 'The Lion King',
    year: 1994,
    mediaType: 'movie',
    difficulty: 'hard',
  },
  {
    id: 'q37',
    statement: 'This series has more than 8 seasons.',
    answer: false,
    title: 'Breaking Bad',
    year: 2008,
    mediaType: 'tv',
    difficulty: 'easy',
  },
  {
    id: 'q38',
    statement: 'This film was released before 2000.',
    answer: false,
    title: 'Gladiator',
    year: 2000,
    mediaType: 'movie',
    difficulty: 'hard',
  },
  {
    id: 'q39',
    statement: 'This film is set in Los Angeles.',
    answer: false,
    title: 'The Social Network',
    year: 2010,
    mediaType: 'movie',
    difficulty: 'medium',
  },
  {
    id: 'q40',
    statement: 'Will Smith starred in this film.',
    answer: false,
    title: 'Django Unchained',
    year: 2012,
    mediaType: 'movie',
    difficulty: 'medium',
  },
  {
    id: 'q41',
    statement: 'This show premiered on Amazon Prime Video.',
    answer: false,
    title: 'Stranger Things',
    year: 2016,
    mediaType: 'tv',
    difficulty: 'easy',
  },
  {
    id: 'q42',
    statement: 'This film is a remake of a 1960s movie.',
    answer: false,
    title: 'Interstellar',
    year: 2014,
    mediaType: 'movie',
    difficulty: 'easy',
  },
  {
    id: 'q43',
    statement: 'This film features time travel as a plot device.',
    answer: false,
    title: 'The Revenant',
    year: 2015,
    mediaType: 'movie',
    difficulty: 'easy',
  },
  {
    id: 'q44',
    statement: 'This series is a Netflix original.',
    answer: false,
    title: 'Game of Thrones',
    year: 2011,
    mediaType: 'tv',
    difficulty: 'easy',
  },
  {
    id: 'q45',
    statement: 'This film was directed by Martin Scorsese.',
    answer: false,
    title: 'No Country for Old Men',
    year: 2007,
    mediaType: 'movie',
    difficulty: 'medium',
  },
]
