import type { MovieListItem, StreamingListItem } from '../types'

export const mockMovieList: MovieListItem[] = [
  {
    id: 1,
    title: 'Inception',
    poster_path: '/9gk7adHYeDvHkCSEqAvQNLV5ucs.jpg',
    backdrop_path: '/s3TBrRGB1iav7gFOCNx3H31MoES.jpg',
    release_date: '2010-07-15',
    vote_average: 8.4,
    vote_count: 32000,
    popularity: 85.5,
    overview: 'A thief who steals corporate secrets through dream-sharing technology.',
    genre_ids: [28, 878, 12],
  },
  {
    id: 2,
    title: 'The Dark Knight',
    poster_path: '/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
    backdrop_path: '/hkBaDkMWbLaf8B1lsWsKX7Ew3Xq.jpg',
    release_date: '2008-07-16',
    vote_average: 9.0,
    vote_count: 28000,
    popularity: 92.0,
    overview: 'Batman must accept one of the greatest psychological tests to fight injustice.',
    genre_ids: [28, 80, 18],
  },
  {
    id: 3,
    title: 'Interstellar',
    poster_path: '/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg',
    backdrop_path: '/xu9zaAevzQ5nnrsXN6JcahLnG4i.jpg',
    release_date: '2014-11-05',
    vote_average: 8.6,
    vote_count: 29000,
    popularity: 78.2,
    overview: 'A team of explorers travel through a wormhole in space.',
    genre_ids: [12, 878, 18],
  },
  {
    id: 4,
    title: 'Dune: Part Two',
    poster_path: '/8b8R8l88Qje9dn9OE8PY05NmxlF.jpg',
    backdrop_path: '/xOMo8BRK7PfcJv9JCnx7s5hj0PX.jpg',
    release_date: '2024-02-28',
    vote_average: 8.3,
    vote_count: 5200,
    popularity: 120.0,
    overview: 'Paul Atreides unites with Chani and the Fremen on a warpath of revenge.',
    genre_ids: [878, 12],
  },
  {
    id: 5,
    title: 'Oppenheimer',
    poster_path: '/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg',
    backdrop_path: '/f0p7TdJnjyBmBLyCC9F4FUtzMAB.jpg',
    release_date: '2023-07-19',
    vote_average: 8.2,
    vote_count: 8100,
    popularity: 95.0,
    overview: 'The story of J. Robert Oppenheimer and the Manhattan Project.',
    genre_ids: [18, 36],
  },
  {
    id: 6,
    title: 'Parasite',
    poster_path: '/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg',
    backdrop_path: '/TU9NIjwzjoKPwQHoHshkFcQUCG.jpg',
    release_date: '2019-05-30',
    vote_average: 8.5,
    vote_count: 22000,
    popularity: 88.0,
    overview: 'Greed and class discrimination threaten the newly formed symbiotic relationship.',
    genre_ids: [35, 53, 18],
  },
]

export const mockStreamingList: StreamingListItem[] = [
  ...mockMovieList.slice(0, 4).map((m) => ({
    id: m.id,
    media_type: 'movie' as const,
    title: m.title,
    poster_path: m.poster_path,
    backdrop_path: m.backdrop_path,
    release_date: m.release_date,
    vote_average: m.vote_average,
    vote_count: m.vote_count,
    popularity: m.popularity,
    overview: m.overview,
    genre_ids: m.genre_ids,
  })),
  {
    id: 100,
    media_type: 'tv',
    title: 'The Last of Us',
    poster_path: '/aUQKIpQV31vwHn8APmD6kPCSJwV.jpg',
    backdrop_path: '/nBRyYTPYU7odF7g5vnt1M3eH2tl.jpg',
    release_date: '2023-01-15',
    vote_average: 8.7,
    vote_count: 4500,
    popularity: 110,
    overview: 'After a global pandemic destroys civilization.',
    genre_ids: [10765, 18],
  },
  {
    id: 101,
    media_type: 'tv',
    title: 'Shōgun',
    poster_path: '/7O4iVfOMQmdCSxhOg1WnzG1AgYT.jpg',
    backdrop_path: '/7O4iVfOMQmdCSxhOg1WnzG1AgYT.jpg',
    release_date: '2024-02-27',
    vote_average: 8.6,
    vote_count: 1200,
    popularity: 95,
    overview: 'In Japan in the year 1600.',
    genre_ids: [18, 36],
  },
]
